### ISSUE TITLE
Do a nearest neighbor from 2 seperate geodataframes

### ISSUE THREAD

**Issue by rbhatia46** [aspectumapp/vincenty-cuda-nns#2]
Hi,
thanks for the amazing package, I am trying to find nearest neighbors from a Geodataframe A(source points) in another Geodataframe B(candidate points), how can I do this using this package?

I want to create a Ball tree on B and then query the nearest neighbor from B for every point in A.
So in a nutshell, I want to build the tree on one set of points(B) and query on another set of points(A).

So I want an interface like - 
```python
cuda_tree = CudaTree(B, leaf_size=4)
distances, indices = cuda_tree.query(A,n_neighbors=2)


```
Any help is appreciated

**Comment by felytic** [comment]
Hi, @rbhatia46 
Thanks for your proposition, it would great do add this functionality to the package.
I've tried to find an easy way to do it this weekend but stuck with a problem. 

The algorithm starts in a point's node and then looks for neighbors within, next it walks through other nodes and compares distances to them. So, for each point, we have to know it's "home" node to start the search. 

And for B, we don't know "home" nodes. I'll try to find an adequate solution to this problem and test it. Most obvious is the Depth-first search for each point, but it makes the algorithm slower.

In any case, I'll let you know about the results.

**Comment by felytic** [comment]
Hi @rbhatia46!
Now you can try to use the interface that you've proposed. You need to install version `0.2.2` to avoid some minor bugs. Note that this version is about 17% slower.
Please let me know if everything works correctly, or there are any issues.
